{{- if .Values.persistence.enabled }}
{{- $old := lookup "v1" "Secret" .Release.Namespace (printf "%s-auth" .Release.Name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels: {app.kubernetes.io/name: {{ .Chart.Name }}, app.kubernetes.io/instance: {{ .Release.Name }}}
  {{- if .Values.persistence.retain }}
  annotations: {helm.sh/resource-policy: keep}
  {{- end }}
type: Opaque
data:
  {{- if $old }}
  password: {{ index $old.data "password" | quote }}
  root-password: {{ index $old.data "root-password" | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
