package kr.co.mcmp.ape.cbtumblebug.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

import java.util.List;

@Data
public class Spec {

    private int acceleratorCount;
    private int acceleratorMemoryGB;
    private String acceleratorModel;
    private String acceleratorType;
    
    @JsonProperty("associatedObjectList")
    private List<String> associatedObjectList;
    
    private String connectionName;
    private double costPerHour;
    private String cspSpecName;
    private String description;
    
    @JsonProperty("evaluationScore01")
    private double evaluationScore01;
    @JsonProperty("evaluationScore02")
    private double evaluationScore02;
    @JsonProperty("evaluationScore03")
    private double evaluationScore03;
    @JsonProperty("evaluationScore04")
    private double evaluationScore04;
    @JsonProperty("evaluationScore05")
    private double evaluationScore05;
    @JsonProperty("evaluationScore06")
    private double evaluationScore06;
    @JsonProperty("evaluationScore07")
    private double evaluationScore07;
    @JsonProperty("evaluationScore08")
    private double evaluationScore08;
    @JsonProperty("evaluationScore09")
    private double evaluationScore09;
    @JsonProperty("evaluationScore10")
    private double evaluationScore10;
    
    private String evaluationStatus;
    private String id;
    private String infraType;
    
    @JsonProperty("isAutoGenerated")
    private boolean isAutoGenerated;
    
    private int maxTotalStorageTiB;
    private int memoryGiB;
    private String name;
    private String namespace;
    private double netBwGbps;
    private int orderInFilteredResult;
    private String osType;
    private String providerName;
    private String regionName;
    private String rootDiskSize;
    private String rootDiskType;
    private int storageGiB;
    private String systemLabel;
    private String uid;
    private int vCPU;
}