package kr.co.mcmp.ape.cbtumblebug.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import java.util.List;

@Data
public class SshKeyResponse {
    
    private List<SshKeyInfo> sshKey;
    
    @Data
    public static class SshKeyIdResponse {
        private List<String> output;
    }
    
    @Data
    public static class SshKeyInfo {
        private String resourceType;
        private String id;
        private String uid;
        private String cspResourceName;
        private String cspResourceId;
        private String name;
        private String connectionName;
        private ConnectionConfig connectionConfig;
        private String description;
        private String fingerprint;
        private String privateKey;
        private String publicKey;
        private List<KeyValue> keyValueList;
        private List<String> associatedObjectList;
        private String systemLabel;
        private String username;
        private String verifiedUsername;
        private boolean isAutoGenerated;
    }
    
    @Data
    public static class ConnectionConfig {
        private String configName;
        private String providerName;
        private String driverName;
        private String credentialName;
        private String credentialHolder;
        private String regionZoneInfoName;
        private RegionZoneInfo regionZoneInfo;
        private RegionDetail regionDetail;
        private boolean regionRepresentative;
        private boolean verified;
    }
    
    @Data
    public static class RegionZoneInfo {
        private String assignedRegion;
        private String assignedZone;
    }
    
    @Data
    public static class RegionDetail {
        private String regionId;
        private String regionName;
        private String description;
        private Location location;
        private List<String> zones;
    }
    
    @Data
    public static class Location {
        private String display;
        private double latitude;
        private double longitude;
    }
    
    @Data
    public static class KeyValue {
        private String key;
        private String value;
    }
}
