package kr.co.mcmp.util;

import java.util.UUID;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.util.ReflectionTestUtils;
import static org.assertj.core.api.Assertions.*;

class BuiltInHelmCatalogTest {
    private JdbcTemplate jdbc;
    private DatabaseInitializer initializer;
    @BeforeEach void setUp() {
        jdbc = new JdbcTemplate(new DriverManagerDataSource("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
        jdbc.execute("""
                CREATE TABLE SOFTWARE_CATALOG (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TITLE VARCHAR, DESCRIPTION VARCHAR, SUMMARY VARCHAR, CATEGORY VARCHAR, MIN_CPU DOUBLE PRECISION,
                RECOMMENDED_CPU DOUBLE PRECISION, MIN_MEMORY DOUBLE PRECISION, RECOMMENDED_MEMORY DOUBLE PRECISION,
                MIN_DISK INTEGER, RECOMMENDED_DISK INTEGER, CPU_THRESHOLD DOUBLE PRECISION, MEMORY_THRESHOLD DOUBLE PRECISION,
                MIN_REPLICAS INTEGER, MAX_REPLICAS INTEGER, HPA_ENABLED BOOLEAN, DEFAULT_PORT INTEGER, INGRESS_ENABLED BOOLEAN,
                CREATED_AT TIMESTAMP, UPDATED_AT TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE HELM_CHART (CATALOG_ID BIGINT UNIQUE, CHART_NAME VARCHAR, CHART_VERSION VARCHAR,
                CHART_REPOSITORY_URL VARCHAR, REPOSITORY_NAME VARCHAR, REPOSITORY_DISPLAY_NAME VARCHAR,
                REPOSITORY_OFFICIAL BOOLEAN, PACKAGE_ID VARCHAR, NORMALIZED_NAME VARCHAR, APP_VERSION VARCHAR,
                DESCRIPTION VARCHAR, CATEGORY VARCHAR, IMAGE_REPOSITORY VARCHAR, TAG VARCHAR, HAS_VALUES_SCHEMA BOOLEAN)
                """);
        jdbc.execute("CREATE TABLE SOFTWARE_CATALOG_REF (CATALOG_ID BIGINT, REF_IDX INTEGER, REF_VALUE VARCHAR, REF_DESC VARCHAR, REF_TYPE VARCHAR)");
        initializer = new DatabaseInitializer();
        ReflectionTestUtils.setField(initializer, "jdbcTemplate", jdbc);
    }
    private void sync() { ReflectionTestUtils.invokeMethod(initializer, "ensureBuiltInHelmCatalogs"); }
    @Test void cleanDatabaseCreatesFiveAndRepeatedStartupIsIdempotent() {
        sync(); sync();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG", Integer.class)).isEqualTo(5);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM HELM_CHART", Integer.class)).isEqualTo(5);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG_REF WHERE REF_VALUE='storage-class'", Integer.class)).isEqualTo(3);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG_REF", Integer.class)).isEqualTo(16);
    }
    @Test void reusesExistingVmCatalogWithoutResettingSettings() {
        jdbc.update("INSERT INTO SOFTWARE_CATALOG (TITLE, DEFAULT_PORT, HPA_ENABLED, MIN_CPU) VALUES ('Redis', 16379, true, 3)");
        sync(); sync();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG WHERE TITLE='Redis'", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT DEFAULT_PORT FROM SOFTWARE_CATALOG WHERE TITLE='Redis'", Integer.class)).isEqualTo(16379);
        assertThat(jdbc.queryForObject("SELECT MIN_CPU FROM SOFTWARE_CATALOG WHERE TITLE='Redis'", Double.class)).isEqualTo(3d);
        assertThat(jdbc.queryForObject("SELECT HPA_ENABLED FROM SOFTWARE_CATALOG WHERE TITLE='Redis'", Boolean.class)).isTrue();
    }
    @Test void neverOverwritesACustomHelmMappingOrAddsOurCapabilitiesToIt() {
        jdbc.update("INSERT INTO SOFTWARE_CATALOG (TITLE) VALUES ('Redis')");
        jdbc.update("INSERT INTO HELM_CHART (CATALOG_ID, CHART_NAME, CHART_REPOSITORY_URL) SELECT ID, 'myredis', 'https://custom.example.org' FROM SOFTWARE_CATALOG");
        sync(); sync();
        assertThat(jdbc.queryForObject("SELECT CHART_NAME FROM HELM_CHART WHERE CATALOG_ID=1", String.class)).isEqualTo("myredis");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG_REF WHERE CATALOG_ID=1", Integer.class)).isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM HELM_CHART", Integer.class)).isEqualTo(5);
    }
}
